### Ćwiczenie: Łapanie wyjątków

W poniższej funkcji `handleInput`, różne rodzaje danych wejściowych mogą prowadzić do wyjątków, które mogą przerwać wykonywanie naszego programu. Twoim zadaniem jest przechwycenie wszystkich możliwych wyjątków i wyświetlenie odpowiednich komunikatów użytkownikowi.
- Jeśli w polu, w którym spodziewana jest liczba użytkownik podał wartość, która nie jest poprawną liczbą, to `toInt` rzuca `NumberFormatException`. W takim przypadku powinieneś wyświetlić "Invalid input: ", i komunikat błędu.
- Jeśli użytkownik podał liczbę, ale druga liczba jest zerem, to rzuca `ArithmeticException`. W takim przypadku powinieneś wyświetlić "Division by zero".
- Jeśli użytkownik podał operator, który nie jest obsługiwany przez nasz kalkulator, to rzuca `IllegalOperatorException`. W takim przypadku powinieneś wyświetlić "Illegal operator: ", i operator, który został podany przez użytkownika.

Kod startowy:

```kotlin
fun handleInput() {
    print("Enter the first number: ")
    val num1 = readln().toInt()
    print("Enter an operator (+, -, *, /): ")
    val operator = readln()
    print("Enter the second number: ")
    val num2 = readln().toInt()

    val result = when (operator) {
        "+" -> num1 + num2
        "-" -> num1 - num2
        "*" -> num1 * num2
        "/" -> num1 / num2
        else -> throw IllegalOperatorException(operator)
    }

    println("Result: $result")
}

class IllegalOperatorException(operator: String) : 
    Exception("Unknown operator: $operator")

fun main() {
    while (true) {
        // Wrap below function call with try-catching block,
        // and handle possible exceptions.
        handleInput()
    }
}
```

Kod startowy znajdziesz w projekcie [kotlin-exercises](https://github.com/MarcinMoskala/kotlin-exercises) na GitHubie w pliku `essentials/exceptions/HandleExceptions.kt`. Możesz sklonować ten projekt i rozwiązać to ćwiczenie lokalnie.
